// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9eiWo8Eadwtw46zacr9r4i
// Component: griCARnu-f
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: 9eiWo8Eadwtw46zacr9r4i/projectcss
import * as sty from "./PlasmicTourCreator.module.css"; // plasmic-import: griCARnu-f/css

export type PlasmicTourCreator__VariantMembers = {};

export type PlasmicTourCreator__VariantsArgs = {};
type VariantPropType = keyof PlasmicTourCreator__VariantsArgs;
export const PlasmicTourCreator__VariantProps = new Array<VariantPropType>();

export type PlasmicTourCreator__ArgsType = {};
type ArgPropType = keyof PlasmicTourCreator__ArgsType;
export const PlasmicTourCreator__ArgProps = new Array<ArgPropType>();

export type PlasmicTourCreator__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultTourCreatorProps {
  className?: string;
}

function PlasmicTourCreator__RenderFunc(props: {
  variants: PlasmicTourCreator__VariantsArgs;
  args: PlasmicTourCreator__ArgsType;
  overrides: PlasmicTourCreator__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTourCreator__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicTourCreator__VariantsArgs;
  args?: PlasmicTourCreator__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicTourCreator__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicTourCreator__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTourCreator__ArgProps,
      internalVariantPropNames: PlasmicTourCreator__VariantProps
    });

    return PlasmicTourCreator__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTourCreator";
  } else {
    func.displayName = `PlasmicTourCreator.${nodeName}`;
  }
  return func;
}

export const PlasmicTourCreator = Object.assign(
  // Top-level PlasmicTourCreator renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTourCreator
    internalVariantProps: PlasmicTourCreator__VariantProps,
    internalArgProps: PlasmicTourCreator__ArgProps
  }
);

export default PlasmicTourCreator;
/* prettier-ignore-end */
